[colors.bright]
black = "0x585858"
blue = "0x7cafc2"
cyan = "0x86c1b9"
green = "0xa1b56c"
magenta = "0xba8baf"
red = "0xab4642"
white = "0xf8f8f8"
yellow = "0xf7ca88"

[colors.cursor]
cursor = "0xd8d8d8"
text = "0xd8d8d8"

[colors.normal]
black = "0x181818"
blue = "0x7cafc2"
cyan = "0x86c1b9"
green = "0xa1b56c"
magenta = "0xba8baf"
red = "0xab4642"
white = "0xd8d8d8"
yellow = "0xf7ca88"

[colors.primary]
background = "0x181818"
foreground = "0xd8d8d8"

[font]
size = 12.0

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[font.normal]
family = "UDEV Gothic 35JPDOC"

[scrolling]
history = 10000
multiplier = 3

[shell]
args = ["-l", "-c", "zellij attach --index 0 --create"]
program = "/bin/zsh"

[window]
decorations = "full"
dynamic_title = true
opacity = 0.9

[window.dimensions]
columns = 120
lines = 56

[window.padding]
x = 8
y = 4
